include $(PROJ_ROOT)/release/customer_tailor/nvr_default.mk
interface_ai:=enable
interface_ao:=enable
interface_gfx:=enable
interface_hdmi:=disable
interface_divp:=enable
interface_disp:=enable
interface_panel:=enable
interface_rgn:=disable
interface_shadow:=enable
interface_uac:=enable
interface_vdf:=enable
interface_vdisp:=enable
interface_vdec:=enable
interface_venc:=enable
interface_wlan:=enable

misc_fbdev:=enable
#mhal
mhal_aio:=enable
mhal_csi:=enable
mhal_disp:=enable
mhal_divp:=enable
mhal_isp:=enable
mhal_ispalgo:=enable
mhal_ispmid:=enable
mhal_ldc:=enable
mhal_mload:=enable
mhal_panel:=enable
#mhal_rgn:=disable
mhal_sensorif:=disable
mhal_venc:=enable
mhal_vif:=disable
mhal_vpe:=disable
mhal_hdmitx:=disable

verify_jpeg2disp=enable
verify_disp_init=enable
verify_bootanimation=enable
#verify_logo=enable

#verify_smarttalk=enable
#verify_ssplayer=enable
#verify_smarthome=enable
#verify_zk_bootup=enable
#verify_zk_mini_security=enable
#verify_zk_mini_security_fastboot=enable
verify_zk_full_security=enable
#verify_zk_full_security_fastboot=enable
