var list={
    "tuijian":[
        {id:"1",name:"甜甜圈",price:"20",url:"./img/ttq.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]
        },
        {id:"2",name:"网红脏脏茶",price:"18",url:"./img/zzc.jpg","describe":"暂无",
            state:[
                {
                    name:"冰度",
                    data:["正常冰","常温","少冰","多冰","去冰"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"3",name:"芒果慕斯蛋糕",price:"42",url:"./img/mgdg.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]
        },
        {id:"4",name:"原味戚风蛋糕",price:"78",url:"./img/zzpic22012.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
            {id:"5",name:"榴莲奶茶",price:"48",url:"./img/llnc.jpg","describe":"暂无",
            state:[
                {
                    name:"冰度",
                    data:["正常冰","常温","少冰"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"6",name:"草莓甜甜圈",price:"25",url:"./img/cm.jpg","describe":"暂无",
        state:[
            {
                name:"冰度",
                data:["正常冰","常温","少冰"]
            },
            {
                name:"甜度",
                data:["正常糖","少糖","多糖"]
            },
        ]},
    ],
    "tea":[
        {id:"1",name:"飞溅的巧克力珍珠奶茶",price:"23",url:"./img/qkl.jpg","describe":"暂无",
            state:[
                {
                    name:"冰度",
                    data:["正常冰","常温","少冰","多冰","去冰"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]
        },
        {id:"2",name:"网红脏脏茶",price:"18",url:"./img/zzc.jpg","describe":"暂无",
            state:[
                {
                    name:"冰度",
                    data:["正常冰","常温","少冰","多冰","去冰"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"3",name:"红豆奶茶",price:"33",url:"./img/hdnc.jpg","describe":"暂无",
            state:[
                {
                    name:"冰度",
                    data:["正常冰","常温","少冰","多冰","去冰"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"4",name:"烧仙草奶茶",price:"18",url:"./img/sxc.jpg","describe":"暂无",
            state:[
                {
                    name:"冰度",
                    data:["正常冰","常温","少冰","多冰","去冰"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"5",name:"榴莲奶茶",price:"48",url:"./img/llnc.jpg","describe":"暂无",
        state:[
            {
                name:"冰度",
                data:["正常冰","常温","少冰"]
            },
            {
                name:"甜度",
                data:["正常糖","少糖","多糖"]
            },
        ]},
        {id:"6",name:"芒果乌龙茶",price:"35",url:"./img/mgwlc.jpg","describe":"暂无",
        state:[
            {
                name:"冰度",
                data:["正常冰","常温","少冰"]
            },
            {
                name:"甜度",
                data:["正常糖","少糖","多糖"]
            },
        ]},
    ],
    "cake":[
        {id:"1",name:"芒果慕斯蛋糕",price:"42",url:"./img/mgdg.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]
        },
        {id:"2",name:"水果奶油纸杯",price:"58",url:"./img/zzpic22832.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"3",name:"杏仁奶油生日蛋糕",price:"63",url:"./img/zzpic22587.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"4",name:"原味戚风蛋糕",price:"78",url:"./img/zzpic22012.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"5",name:"巧克力慕斯小蛋糕",price:"65",url:"./img/zzpic21672.jpg","describe":"暂无",
        state:[
            {
                name:"规格",
                data:["小","中","大"]
            },
            {
                name:"甜度",
                data:["正常糖","少糖","多糖"]
            },
        ]},
        {id:"6",name:"奶油草莓水果蛋糕",price:"35",url:"./img/zzpic20235.jpg","describe":"暂无",
        state:[
            {
                name:"规格",
                data:["小","中","大"]
            },
            {
                name:"甜度",
                data:["正常糖","少糖","多糖"]
            },
        ]},
    ],
    "donuts":[
        {id:"1",name:"香甜诱人甜甜圈",price:"23",url:"./img/xtyr.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]
        },
        {id:"2",name:"法式甜甜圈",price:"18",url:"./img/fs.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"3",name:"甜甜圈",price:"20",url:"./img/ttq.jpg","describe":"暂无",
            state:[
                {
                    name:"规格",
                    data:["小","中","大"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
        {id:"6",name:"草莓甜甜圈",price:"25",url:"./img/cm.jpg","describe":"暂无",
            state:[
                {
                    name:"冰度",
                    data:["正常冰","常温","少冰"]
                },
                {
                    name:"甜度",
                    data:["正常糖","少糖","多糖"]
                },
            ]},
    ],
}